### ISSUE TITLE
Use password securely

### ISSUE THREAD

**Issue by urielha** [Krumpet/OVSDownloader#1]
Hi, 
Could you please edit your script to **read** and **store** the password using secureString?
This is not perfect solution but gives minimum of privacy :)

You need to change two things:

Reading from user using `-assecurestring` flag and `convertFrom-SecureString` : 

```powershell
$Pass = Read-Host -assecurestring -Prompt "Please insert password" | ConvertFrom-SecureString
```

Reading from file is little "hacky" but works:

```powershell
$hash = Get-Content -Raw ".\params.txt" | ConvertFrom-StringData
$securePass = ConvertTo-SecureString -String $hash["password"]
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($securePass)
$hash["password"] = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
return $hash
```

I edited your script to support this and if you want I can open a pull request with the changes.

**Comment by Krumpet** [comment]
Hey, I was thinking of adding `-assecurestring` and `ConvertFrom` and `ConvertTo`, but the second part I'm unfamiliar with. I'll read about it.
Go ahead with these changes, and thanks!

EDIT: Having read about it, this is indeed the correct way to get the password into plaintext, for insertion into the hash table.

Note however that `[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($BSTR)` is needed after using `$BSTR`, apparently for security reasons.
