### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by bron1993** [Krumpet/OVSDownloader#3]
After inserting username and password, and trying to input a course URL, I get an error - 'Invalid URL'

This error appears no matter which course link I insert, even copying the example URL gives this error.

This is new, since I used the program successfully before.

Image:
![image](https://user-images.githubusercontent.com/33197584/32143599-80e19f12-bcb4-11e7-8fcf-1768fdda0181.png)

@Krumpet

**Comment by Krumpet** [comment]
Hi, I tried this today on a different computer than the one I develop on and it worked for me. Coukd you try:
1. Deleting params.txt and inputting username and password again
2. Trying to use the app on another computer
3. Letting someone else try with their account on your computer

Please get back to me once you've tried, and let me know if anything worked.

**Comment by bron1993** [comment]
Works on a different computer...
I will update if I find a solution for the other one

Thank you @Krumpet
