### ISSUE TITLE
New authentication method

### ISSUE THREAD

**Issue by bron1993** [Krumpet/OVSDownloader#4]
Hi again :)

Will the script be updated to support the new authentication method?
Currently crashes when entering Course link.
"Error: No files found. Exiting with code 5, press any key. . ."

Thanks :)

**Comment by Krumpet** [comment]
Hi, there's a new project that works after the change to the authentication method - see
https://github.com/Krumpet/OVSDownloader-GUI

I'll make a note that this project is deprecated.
